import jinja2

ORACLE_RESERVED_WORDS = [
    "ACCESS","ELSE","MODIFY","START", "ADD","EXCLUSIVE","NOAUDIT","SELECT",
    "ALL","EXISTS","NOCOMPRESS","SESSION", "ALTER","FILE","NOT","SET",
    "AND","FLOAT","NOTFOUND","SHARE", "ANY","FOR","NOWAIT","SIZE",
    "ARRAYLEN","FROM","NULL","SMALLINT", "AS","GRANT","NUMBER","SQLBUF",
    "ASC","GROUP","OF","SUCCESSFUL", "AUDIT","HAVING","OFFLINE","SYNONYM",
    "BETWEEN","IDENTIFIED","ON","SYSDATE", "BY","IMMEDIATE","ONLINE","TABLE",
    "CHAR","IN","OPTION","THEN", "CHECK","INCREMENT","OR","TO",
    "CLUSTER","INDEX","ORDER","TRIGGER", "COLUMN","INITIAL","PCTFREE","UID",
    "COMMENT","INSERT","PRIOR","UNION", "COMPRESS","INTEGER","PRIVILEGES","UNIQUE",
    "CONNECT","INTERSECT","PUBLIC","UPDATE", "CREATE","INTO","RAW","USER",
    "CURRENT","IS","RENAME","VALIDATE", "DATE","LEVEL","RESOURCE","VALUES",
    "DECIMAL","LIKE","REVOKE","VARCHAR", "DEFAULT","LOCK","ROW","VARCHAR2",
    "DELETE","LONG","ROWID","VIEW", "DESC","MAXEXTENTS","ROWLABEL","WHENEVER",
    "DISTINCT","MINUS","ROWNUM","WHERE", "DROP","MODE","ROWS","WITH"
]

ORACLE_KEYWORDS = [
    "ADMIN", "AFTER", "ALLOCATE", "ANALYZE", "ARCHIVE", "ARCHIVELOG", "AUTHORIZATION", "AVG", "BACKUP",
    "BECOME", "BEFORE", "BEGIN", "BLOCK", "BODY", "CACHE", "CANCEL", "CASCADE", "CHANGE",
    "CHARACTER", "CHECKPOINT", "CLOSE", "COBOL", "COMMIT", "COMPILE", "CONSTRAINT", "CONSTRAINTS", "CONTENTS",
    "CONTINUE", "CONTROLFILE", "COUNT", "CURSOR", "CYCLE", "DATABASE", "DATAFILE", "DBA", "DEC",
    "DECLARE", "DISABLE", "DISMOUNT", "DOUBLE", "DUMP", "EACH", "ENABLE", "END", "ESCAPE",
    "EVENTS", "EXCEPT", "EXCEPTIONS", "EXEC", "EXECUTE", "EXPLAIN", "EXTENT", "EXTERNALLY", "FETCH",
    "FLUSH", "FORCE", "FOREIGN", "FORTRAN", "FOUND", "FREELIST", "FREELISTS", "FUNCTION", "GO", "GOTO",
    "GROUPS", "INCLUDING", "INDICATOR", "INITRANS", "INSTANCE", "INT", "KEY", "LANGUAGE", "LAYER", "LINK",
    "LISTS", "LOGFILE", "MANAGE", "MANUAL", "MAX", "MAXDATAFILES", "MAXINSTANCES", "MAXLOGFILES", "MAXLOGHISTORY",
    "MAXLOGMEMBERS", "MAXTRANS", "MAXVALUE", "MIN", "MINEXTENTS", "MINVALUE", "MODULE", "MOUNT", "NEW", "NEXT",
    "NOARCHIVELOG", "NOCACHE", "NOCYCLE", "NOMAXVALUE", "NOMINVALUE", "NONE", "NOORDER", "NORESETLOGS", "NORMAL",
    "NOSORT", "NUMERIC", "OFF", "OLD", "ONLY", "OPEN", "OPTIMAL", "OWN", "PACKAGE", "PARALLEL", "PCTINCREASE",
    "PCTUSED", "PLAN", "PLI", "PRECISION", "PRIMARY", "PRIVATE", "PROCEDURE",
    "PROFILE","SAVEPOINT","SQLSTATE","TRACING","QUOTA","SCHEMA","STATEMENT_ID","TRANSACTION","READ","SCN",
    "STATISTICS","TRIGGERS","REAL","SECTION","STOP","TRUNCATE","RECOVER","SEGMENT","STORAGE","UNDER",
    "REFERENCES","SEQUENCE","SUM","UNLIMITED","REFERENCING","SHARED","SWITCH","UNTIL","RESETLOGS",
    "SNAPSHOT","SYSTEM","USE","RESTRICTED","SOME","TABLES","USING","REUSE","SORT","TABLESPACE",
    "WHEN","ROLE","SQL","TEMPORARY","WRITE","ROLES","SQLCODE","THREAD","WORK","ROLLBACK","SQLERROR","TIME"
]

ORACLE_PLSQL_RESERVED_WORDS = [
    "ABORT","BETWEEN","CRASH","DIGITS","ACCEPT","BINARY_INTEGER",
    "CREATE","DISPOSE","ACCESS","BODY","CURRENT","DISTINCT","ADD","BOOLEAN","CURRVAL","DO","ALL","BY",
    "CURSOR","DROP","ALTER","CASE","DATABASE","ELSE","AND","CHAR","DATA_BASE","ELSIF","ANY","CHAR_BASE",
    "DATE","END","ARRAY","CHECK","DBA","ENTRY","ARRAYLEN","CLOSE","DEBUGOFF","EXCEPTION","AS",
    "CLUSTER","DEBUGON","EXCEPTION_INIT","ASC","CLUSTERS","DECLARE","EXISTS","ASSERT","COLAUTH","DECIMAL",
    "EXIT","COLUMNS","DEFAULT","FALSE","AT","COMMIT","DEFINITION","FETCH","AUTHORIZATION",
    "COMPRESS","DELAY","FLOAT","AVG","CONNECT","DELETE","FOR","BASE_TABLE","CONSTANT","DELTA","FORM",
    "BEGIN","COUNT","DESC","FROM","FUNCTION","NEW","RELEASE","SUM","GENERIC","NEXTVAL","REMR","TABAUTH",
    "GOTO","NOCOMPRESS","RENAME","TABLE","GRANT","NOT","RESOURCE","TABLES","GROUP","NULL","RETURN",
    "TASK","HAVING","NUMBER","REVERSE","TERMINATE","IDENTIFIED","NUMBER_BASE","REVOKE","THEN","IF","OF",
    "ROLLBACK","TO","IN","ON","ROWID","TRUE","INDEX","OPEN","ROWLABEL","TYPE","INDEXES","OPTION","ROWNUM",
    "UNION","INDICATOR","OR","ROWTYPE","UNIQUE","INSERT","ORDER","RUN","UPDATE","INTEGER","OTHERS",
    "SAVEPOINT","USE","INTERSECT","OUT","SCHEMA","VALUES","INTO","PACKAGE","SELECT","VARCHAR","IS","PARTITION",
    "SEPARATE","VARCHAR2","LEVEL","PCTFREE","SET","VARIANCE","LIKE","POSITIVE","SIZE","VIEW","LIMITED",
    "PRAGMA","SMALLINT","VIEWS","LOOP","PRIOR","SPACE","WHEN","MAX","PRIVATE","SQL","WHERE","MIN","PROCEDURE",
    "SQLCODE","WHILE","MINUS","PUBLIC","SQLERRM","WITH","MLSLABEL","RAISE","START","WORK","MOD","RANGE",
    "STATEMENT","XOR","MODE","REAL","STDDEV","NATURAL","RECORD","SUBTYPE","NOCOPY"
]

ORACLE_TYPES = [
    "ANYDATA", "ANYTYPE", "BINARY_DOUBLE", "BINARY_FLOAT", "BLOB", "BOOLEAN", "CHAR", "CLOB", "DATE", "DSINTERVAL_UNCONSTRAINED",
    "INTEGER", "INTERVAL\s+DAY\s+TO\s+SECOND", "LONG", "NCHAR", "NUMBER", "PLS_INTEGER", "RAW", "SIMPLE_INTEGER",
    "SYS_REFCURSOR", "TIMESTAMP", "TIMESTAMP\s+WITH\s+LOCAL\s+TIME\s+ZONE", "TIMESTAMP\s+WITH\s+TIME\s+ZONE",
    "TIMESTAMP_LTZ_UNCONSTRAINED", "TIMESTAMP_TZ_UNCONSTRAINED", "TIMESTAMP_UNCONSTRAINED", "VARCHAR2"
]

ORACLE_BUILTIN_FUNCTIONS = [
    "ABS", "ACOS", "ADD_MONTHS", "ASCII", "ASCIISTR", "ASIN", "ATAN", "ATAN2", "AVG", "BFILENAME", "BIN_TO_NUM", "BITAND", "CARDINALITY", "CAST", "CEIL", "CHARTOROWID", "CHR", "COALESCE", "COMPOSE", "CONCAT", "CONVERT", "CORR", "COS", "COSH", "COUNT", "COVAR_POP", "COVAR_SAMP", "CUME_DIST", "CURRENT_DATE", "CURRENT_TIMESTAMP", "DBTIMEZONE", "DECODE", "DECOMPOSE", "DENSE_RANK", "DUMP", "EMPTY_BLOB", "EMPTY_CLOB", "EXP", "EXTRACT", "FIRST_VALUE", "FLOOR",
    "FROM_TZ", "GREATEST", "GROUP_ID", "HEXTORAW", "INITCAP", "INSTR", "INSTR2", "INSTR4", "INSTRB", "INSTRC", "LAG", "LAST_DAY", "LAST_VALUE", "LEAD", "LEAST", "LENGTH", "LENGTH2", "LENGTH4", "LENGTHB", "LENGTHC", "LISTAGG", "LN", "LNNVL", "LOCALTIMESTAMP", "LOG", "LOWER", "LPAD", "LTRIM", "MAX", "MEDIAN", "MIN", "MOD", "MONTHS_BETWEEN", "NANVL", "NCHR", "NEW_TIME", "NEXT_DAY", "NTH_VALUE", "NULLIF", "NUMTODSINTERVAL",
    "NUMTOYMINTERVAL","NVL","NVL2","POWER","RANK","RAWTOHEX","REGEXP_COUNT","REGEXP_INSTR","REGEXP_REPLACE","REGEXP_SUBSTR","REMAINDER","REPLACE","ROUND","ROWNUM","RPAD","RTRIM","SESSIONTIMEZONE","SIGN","SIN","SINH","SOUNDEX","SQLCODE","SQLERRM","SQRT","STDDEV","SUBSTR","SUM","SYS_CONTEXT","SYSDATE","SYSTIMESTAMP","TAN","TANH","TO_CHAR","TO_CLOB","TO_DATE","TO_DSINTERVAL","TO_LOB", "TO_MULTI_BYTE",
    "TO_NCLOB","TO_NUMBER","TO_SINGLE_BYTE","TO_TIMESTAMP","TO_TIMESTAMP_TZ","TO_YMINTERVAL","TRANSLATE","TRIM","TRUNC","TZ_OFFSET","UID","UPPER","USER","USERENV","VAR_POP","VAR_SAMP","VARIANCE","VSIZE"
]

context = {
    "p_ext_list"    : ["ddl", "dml", "pkb", "pks", "seq", "sql", "tab", "tpb", "tps", "tst", "vw"],
    "p_uuid"        : "28DCE4DD-F5E1-4ED3-8847-64DA6B1F9163",
    "keyword_list"  : sorted(list(set(ORACLE_RESERVED_WORDS + ORACLE_KEYWORDS + ORACLE_PLSQL_RESERVED_WORDS))),
    "identifier"    : "[a-z0-9_\"#$]+",
    "type_list"     : sorted(list(set(ORACLE_TYPES))),
    "function_list" : sorted(list(set(ORACLE_BUILTIN_FUNCTIONS))),
}

def main():
    env = jinja2.Environment(
        loader        = jinja2.FileSystemLoader("src/main/resources/templates"),
        trim_blocks   = True,
        lstrip_blocks = True,
        extensions    = ["jinja2.ext.do"]
    )
    templ = env.get_template("PLSQL.tmLanguage")
    out = templ.render(context)
    with open("PLSQL.tmLanguage", "w+") as f:
        f.write(out)

if __name__ == "__main__":
    main()
